title: [ 不能胜任岗位者 徐大伟(davidxu)! AMS PTP效能中心前总监 ]

description: 徐大伟连一年经验的工程师都不如!

theme: jekyll-theme-tactile

github:
  zip_url: http://example.com/download.zip
  repository_url: http://example.com/download.zip
  another_url: another value
