title: 昏庸无能 无管理能力也无技术特长 徐大伟(davidxu)! AMS PTP效能中心前总监
description: 徐大伟连一年经验的工程师都不如!

theme: jekyll-theme-slate

github:
  zip_url: http://example.com/download.zip
  repository_url: http://example.com/download.zip
  another_url: another value
